name: neural-nlp
channels:
- defaults
dependencies:
  - python>=3.6
  - tensorflow
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - nltk
  - gensim
  - theano
  - pip:
    - git+https://github.com/mschrimpf/brain-score.git
    - git+https://github.com/mschrimpf/caching
    - pillow
    - llist
    - git+https://github.com/mschrimpf/skip-thoughts.git
    - git+https://github.com/mschrimpf/lm_1b.git
    - nbsvm
